CREATE TABLE  "AD_ALINHAMENTO" 
   ("ID_ALINHAMENTO" NUMBER(5,0) NOT NULL ENABLE, 
	"ID_COLABORADOR" NUMBER(4,0) NOT NULL ENABLE, 
	"ID_COLABORADOR_AVALIADOR" NUMBER(4,0) NOT NULL ENABLE, 
	"DT_REFERENCIA" DATE NOT NULL ENABLE, 
	"DT_ALINHAMENTO" DATE, 
	"DT_REGISTRO" DATE DEFAULT NULL, 
	"DESCRICAO_1" VARCHAR2(4000), 
	"DESCRICAO_2" VARCHAR2(4000), 
	"DESCRICAO_3" VARCHAR2(4000), 
	"OBSERVACAO" VARCHAR2(4000), 
	 CONSTRAINT "PK_AD_ALINHAMENTO" PRIMARY KEY ("ID_ALINHAMENTO")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "AD_ALINHAMENTO" ADD CONSTRAINT "FK_AD_ALINH_COLAB_AVALIADO" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES  "AD_USUARIO" ("ID") ENABLE
/
ALTER TABLE  "AD_ALINHAMENTO" ADD CONSTRAINT "FK_AD_ALINH_COLAB_AVALIADOR" FOREIGN KEY ("ID_COLABORADOR_AVALIADOR")
	  REFERENCES  "AD_USUARIO" ("ID") ENABLE
/


CREATE OR REPLACE EDITIONABLE TRIGGER  "TRG_AD_ALINHAMENTO" 
  before insert on ad_alinhamento 
  referencing old as old new as new 
  for each row 
begin 
  select nvl(max(id_alinhamento), 0) + 1 
    into :new.id_alinhamento 
    from ad_alinhamento; 
end; 

/
ALTER TRIGGER  "TRG_AD_ALINHAMENTO" ENABLE
/


