CREATE TABLE  "AD_DIRETORIA_LOTACAO" 
   ("ID_DIRETORIA_LOTACAO" NUMBER(4,0) NOT NULL ENABLE, 
	"ID_DIRETORIA" NUMBER(4,0) NOT NULL ENABLE, 
	"ID_LOTACAO" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "AD_DIRETORIA_LOTACAO_PK" PRIMARY KEY ("ID_DIRETORIA_LOTACAO")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "AD_DIRETORIA_LOTACAO" ADD CONSTRAINT "AD_DIRETORIA_LOTACAO_FK" FOREIGN KEY ("ID_DIRETORIA")
	  REFERENCES  "AD_DIRETORIA" ("ID_DIRETORIA") ENABLE
/


CREATE UNIQUE INDEX  "AD_DIRETORIA_LOTACAO_UK" ON  "AD_DIRETORIA_LOTACAO" ("ID_DIRETORIA", "ID_LOTACAO")
/


CREATE OR REPLACE EDITIONABLE TRIGGER  "TRG_AD_DIRETORIA_LOTACAO" 
  before insert or update on AD_DIRETORIA_LOTACAO 
  referencing old as old new as new 
  for each row 
declare 
 
begin 
  if inserting then 
    select SEQ_AD_DIRETORIA_LOTACAO.nextval 
      into :new.ID_DIRETORIA_LOTACAO 
      from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "TRG_AD_DIRETORIA_LOTACAO" ENABLE
/
