CREATE TABLE  "AD_DIARIO_AVALIACAO" 
   ("ID_DIARIO_AVALIACAO" NUMBER(5,0) NOT NULL ENABLE, 
	"ID_COLABORADOR" NUMBER(4,0) NOT NULL ENABLE, 
	"ID_COLABORADOR_AVALIADOR" NUMBER(4,0) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(4000) NOT NULL ENABLE, 
	"DT_ACONTECIMENTO" DATE, 
	"DT_REGISTRO" DATE DEFAULT sysdate, 
	"ID_AVALIACAO" NUMBER(6,0), 
	"ANEXO" BLOB, 
	"ATTACH_FILENAME" VARCHAR2(255), 
	"ATTACH_MIMETYPE" VARCHAR2(255), 
	"NM_ARQUIVO_SALVO" VARCHAR2(255), 
	"ID_PERFIL_REGISTRO" NUMBER(1,0), 
	 PRIMARY KEY ("ID_DIARIO_AVALIACAO")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "AD_DIARIO_AVALIACAO" ADD CONSTRAINT "FK_AD_AVALIACAO_DIARIO" FOREIGN KEY ("ID_AVALIACAO")
	  REFERENCES  "AD_AVALIACAO" ("ID") ENABLE
/
ALTER TABLE  "AD_DIARIO_AVALIACAO" ADD CONSTRAINT "FK_AD_DIARIO_COLAB_AVALIADO" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES  "AD_USUARIO" ("ID") ENABLE
/
ALTER TABLE  "AD_DIARIO_AVALIACAO" ADD CONSTRAINT "FK_AD_DIARIO_COLAB_AVALIADOR" FOREIGN KEY ("ID_COLABORADOR_AVALIADOR")
	  REFERENCES  "AD_USUARIO" ("ID") ENABLE
/


CREATE OR REPLACE EDITIONABLE TRIGGER  "TRG_AD_DIARIO_AVALIACAO" 
  before insert on ad_diario_avaliacao 
  referencing old as old new as new 
  for each row 
begin 
  select nvl(max(id_diario_avaliacao), 0) + 1 
    into :new.id_diario_avaliacao 
    from ad_diario_avaliacao; 
  -- 
  :new.dt_registro := sysdate; 
  -- 
  if :new.id_colaborador_avaliador is null and :new.id_perfil_registro = 1 then 
     :new.id_colaborador_avaliador := PCK_AD.FNC_BUSCA_ID_GERENTE_COLABORADOR(:new.id_colaborador); 
  end if; 
end; 

/
ALTER TRIGGER  "TRG_AD_DIARIO_AVALIACAO" ENABLE
/
