CREATE TABLE  "AD_INDICADOR" 
   ("ID_COMPETENCIA" NUMBER(3,0) NOT NULL ENABLE, 
	"ID" NUMBER(3,0) NOT NULL ENABLE, 
	"NM_COMPETENCIA" VARCHAR2(40) NOT NULL ENABLE, 
	"DS_COMPETENCIA" VARCHAR2(800) NOT NULL ENABLE, 
	"TP_INDICADOR" VARCHAR2(1), 
	"DS_CONCEITO_1" VARCHAR2(800), 
	"DS_CONCEITO_2" VARCHAR2(800), 
	"DS_CONCEITO_3" VARCHAR2(800), 
	"DS_CONCEITO_4" VARCHAR2(800), 
	"TP_AVALIACAO" NUMBER(1,0), 
	"ID_INDICADOR" NUMBER, 
	 CONSTRAINT "AD_CK_TP" CHECK ( tp_indicador in ('E','G') ) ENABLE, 
	 CONSTRAINT "AD_CK_TP_AVALIACAO" CHECK (tp_avaliacao in (1,2,3,4)) ENABLE, 
	 CONSTRAINT "AD_INDICADOR_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "AD_INDICADOR" ADD CONSTRAINT "AD_INDICADOR_CON" FOREIGN KEY ("ID_COMPETENCIA")
	  REFERENCES  "AD_COMPETENCIA" ("ID") ENABLE
/


CREATE OR REPLACE EDITIONABLE TRIGGER  "TRG_AD_INDICADOR_ID" 
  before insert or update on AD_INDICADOR 
  referencing old as old new as new 
  for each row 
declare 
 
begin 
  if inserting then 
    select MAX(ID)+1 
      into :new.ID 
      from AD_INDICADOR; 
  end if; 
end; 


/
ALTER TRIGGER  "TRG_AD_INDICADOR_ID" ENABLE
/
