CREATE TABLE  "AD_USUARIO" 
   ("ID" NUMBER(4,0) NOT NULL ENABLE, 
	"NM_USUARIO" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_PERFIL" NUMBER(1,0) NOT NULL ENABLE, 
	"ID_ADMINISTRADOR" NUMBER(1,0), 
	"AVATAR" BLOB, 
	"ID_ATIVO" NUMBER, 
	"ID_CARGO" NUMBER, 
	"DT_ADMISSAO" DATE, 
	"CARGO" VARCHAR2(51), 
	"NM_LOTACAO" VARCHAR2(25), 
	"DS_LOTACAO" VARCHAR2(100), 
	"ID_FUNCAO" NUMBER, 
	"NOME_USUARIO" VARCHAR2(100), 
	 CONSTRAINT "AD_USUARIO_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AD_USUARIO_CHK_PERFIL" CHECK (ID_PERFIL IN(1,2,3,4,5,6)) ENABLE
   )
/


CREATE UNIQUE INDEX  "AD_USUARIO_UK" ON  "AD_USUARIO" ("NM_USUARIO")
/


