CREATE TABLE  "HP_CARGOS" 
   ("CARGO_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"COLABORADOR_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"DS_CARGO" VARCHAR2(200), 
	"DS_LOTACAO" VARCHAR2(100), 
	"DS_PERIODO" VARCHAR2(100), 
	"DS_ATIVIDADES" VARCHAR2(4000), 
	"PERCENTUAL" NUMBER(5,2) DEFAULT 1, 
	"DT_INICIO" DATE, 
	"DT_FIM" DATE, 
	"LOTACAO_ID" NUMBER(4,0), 
	"TIPO_CARGO_ID" NUMBER(2,0), 
	"TIPO_CARGO_ESPEC_ID" NUMBER(2,0), 
	"ID_REPRESENTACAO" NUMBER, 
	"TERMO_POSSE" BLOB, 
	"TERM_ATTACH_MIMETYPE" VARCHAR2(255), 
	"TERM_ATTACH_FILENAME" VARCHAR2(255), 
	"TERM_ATTACH_CHARSET" VARCHAR2(255), 
	"TERM_ATTACH_LAST_UPDATE" DATE, 
	"CARGO_ATTACH" BLOB, 
	"CARGO_ATTACH_MIMETYPE" VARCHAR2(255), 
	"CARGO_ATTACH_FILENAME" VARCHAR2(255), 
	"CARGO_ATTACH_CHARSET" VARCHAR2(255), 
	"CARGO_ATTACH_LAST_UPDATE" DATE, 
	 CONSTRAINT "HP_CARGOS_PK" PRIMARY KEY ("CARGO_ID")
  USING INDEX  ENABLE
   )
/