
Table
	
Data
	
Indexes
	
Model
	
Constraints
	
Grants
	
Statistics
	
UI Defaults
	
Triggers
	
Dependencies
	
SQL
	
REST
	
Sample Queries
	

CREATE TABLE  "HP_COLABORADORES" 
   ("COLABORADOR_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"NM_USUARIO" VARCHAR2(40) NOT NULL ENABLE, 
	"EMP_COD" NUMBER(2,0) NOT NULL ENABLE, 
	"PAR_MATR" NUMBER(6,0) NOT NULL ENABLE, 
	"ID_ADMINISTRADOR" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"ID_ATIVO" NUMBER(1,0) DEFAULT 1, 
	"ID_GERENTE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"DS_CENTRO_CUSTO" VARCHAR2(40), 
	"LOTACAO_ID" NUMBER(4,0), 
	"VL_TICKET_ALIMENTACAO" NUMBER(8,2), 
	"VL_TICKET_REFEICAO" NUMBER(8,2), 
	"DT_ATUAL_HISTORICO" DATE, 
	"ID_CONSELHEIRO" NUMBER(1,0) DEFAULT 0, 
	"ID_ESTAGIARIO" NUMBER(1,0) DEFAULT 0, 
	"TIPO_TICKET" NUMBER(2,0) DEFAULT null, 
	"CENTRO_CUSTO_ID" NUMBER(4,0), 
	"NOME" VARCHAR2(30), 
	"SEXO" VARCHAR2(1), 
	"DT_NASCIMENTO" DATE, 
	"DT_ULTIMA_ADMISSAO" DATE, 
	"DT_RESCISAO" DATE, 
	"ID_TICKET_CPF" NUMBER(1,0) DEFAULT 0, 
	"ID_CARGO" NUMBER(2,0), 
	"ID_NIVEL_CARGO" NUMBER(1,0), 
	"ID_STEP" NUMBER(2,0), 
	"VL_SALARIO" NUMBER(7,2), 
	"PAR_CPF" NUMBER(11,0), 
	"ID_CONSULTA" NUMBER(1,0) DEFAULT 0, 
	"NR_RAMAL_CELOS" NUMBER(4,0), 
	"ID_AV_ORC_TREINAMENTO" NUMBER(1,0) DEFAULT 0, 
	"NR_NIVEL_STEP" NUMBER(1,0), 
	 CONSTRAINT "HP_COLABORADORES_CHK_ADMIN" CHECK (ID_ADMINISTRADOR IN (0, 1)) ENABLE, 
	 CONSTRAINT "HP_COLABORADORES_CHK_GERENTE" CHECK (ID_GERENTE IN (0, 1)) ENABLE, 
	 CONSTRAINT "HP_COLABORADORES_CHK_CCUSTO" CHECK (ds_centro_custo IN ('ADM','INVEST','SAÚDE','ESTÁGIO-ADM','ESTÁGIO-INVEST','ESTÁGIO-SAÚDE')) ENABLE, 
	 CONSTRAINT "HP_COLABORADORES_CHK_NIVELSTEP" CHECK (NR_NIVEL_STEP IN (1,2,3)) ENABLE, 
	 CONSTRAINT "HP_COLABORADORES_PK" PRIMARY KEY ("COLABORADOR_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "HP_COLBAORADORES_EMP_MATR_UK" UNIQUE ("EMP_COD", "PAR_MATR")
  USING INDEX  ENABLE
   )
/


