CREATE TABLE  "HP_LOTACAO" 
   ("LOTACAO_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"NM_LOTACAO" VARCHAR2(25) NOT NULL ENABLE, 
	"DS_LOTACAO" VARCHAR2(100) NOT NULL ENABLE, 
	"CENTRO_CUSTO_ID" NUMBER(4,0), 
	"DT_FIM" DATE, 
	 CONSTRAINT "HP_LOTACAO_PK" PRIMARY KEY ("LOTACAO_ID")
  USING INDEX  ENABLE
   )
/