CREATE TABLE  "V_AD_DADOS_USUARIOS" 
   ("COLABORADOR_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"PAR_MATR" NUMBER, 
	"NM_USUARIO" VARCHAR2(40) NOT NULL ENABLE, 
	"NOME" VARCHAR2(30), 
	"DS_EMAIL" VARCHAR2(200), 
	"ID_GERENTE" NUMBER(1,0) NOT NULL ENABLE, 
	"DT_ADMISSAO" DATE, 
	"LOTACAO_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"NM_LOTACAO" VARCHAR2(25) NOT NULL ENABLE, 
	"DS_LOTACAO" VARCHAR2(100) NOT NULL ENABLE, 
	"ID_CARGO" NUMBER(2,0), 
	"CARGO" VARCHAR2(51), 
	"ID_ATIVO" NUMBER
   )
/